debtcollective/student-debt-campaign

src/components/Header/api.js, src/components/Header/index.js, src/components/Header/style.scss, src/styles/index.scss
**What:**
Add a dropdown on the profile avatar for logged user in order to display actions such as new **logout** option
**Why:**
Closes #49 
**How:**
Use the same approach as the one at https://github.com/debtcollective/dc-vue-header/blob/341ff1efb8778296682b10a1fef2324bd8e4f90f/src/services/ProfileService.js#L32-L40
https://www.loom.com/share/9b0bae05d7034967852f842524ccf49a
=> Allow user to trigger logout action from the site

.env.example, gatsby-config.js, package.json, yarn.lock
**What:** Add Sentry
**Why:** To have error tracking in the website
**How:**
- Integrate Gatsby with Sentry using [gatsby-plugin-sentry](https://github.com/octalmage/gatsby-plugin-sentry)
=> feat(sentry): add sentry

package.json, src/sections/Notification/index.js, yarn.lock
**What:**
Avoid to show the time within notification date
**Why:**
Closes #68 
**How:**
- Add dayjs to handle formats and use it c1fd24c
**Besides:** we have added flow-typed within the notification component
=> Notification update

flow-typed/JoinCampaign.js, flow-typed/cms.js, flow-typed/faq.js, src/cms/cms.js, src/cms/preview-templates/IndexPagePreview.js, src/components/Join/index.js, src/pages/app.js, src/sections/CTA/index.js, src/sections/FAQ/index.js, src/sections/Join/index.js, src/templates/index-page.js
**What:**
Update the preview of the content within the admin CMS in order to make it visible. **nevertheless, we still missing the live editing functionality**
**Why:**
re #47 
**How:**
- Restore the `Preview` component for the home page 829cdf4
- Add support for fonts and images to be rendered properly 8470d41 7f9d933
**Notes:** we also add more flow definitions to improve the developing flow
=> CMS Preview update

src/components/DataDuesAction/fields.js, src/components/DataDuesAction/index.js
**What:**
Introducing changes to work with react-hook-form 4. Release notes include the breaking changes list 
**Why:**
Close #109
**How:**
making changes noted in the release notes https://github.com/react-hook-form/react-hook-form/releases/tag/v4.0.0
=> fix(react-hook-form): fix breaking changes in react-hook-form 4

src/styles/functions.scss, src/styles/index.scss
**What:**
Avoid warnings when server starts
**Why:**
Closes #67 
**How:**
- Avoid use deprecated fn e99ab8d
=> Remove bootstrap warnings

src/components/Footer/index.js, src/components/Layout.js, src/styles/layout.scss
**What:**
Make the footer to be sticky to the bottom
**Why:**
Closes #79
**How:**
https://css-tricks.com/couple-takes-sticky-footer/#article-header-id-3
=> feat(footer): allow to make the footer stick to bottom

src/sections/Hero/index.js, src/sections/Hero/style.scss, src/sections/Join/index.js, src/styles/type.scss, src/styles/variables.scss, src/templates/index-page.js
**What:**
- Add a new message with total count of people joined 29536e9
**Why:**
https://debtcollective.slack.com/archives/CQ3V1F7C2/p1581048319068800
**How:**
We use the same criteria we have for the counters and sum them all to create the total
**Extras:**
- Change strategy of bump numbers to be fixed to +40 796b58f
- Fix hero circles link on mobile since there where missing margins fcf2402
=> Add new hero headline

src/sections/Hero/index.js, src/sections/Join/index.js
**What:**
remove counter bump
**Why:**
We don't need this anymore, we have more than 500 users atm
**How:**
- Remove bump code
=> dev: remove counter bump

gatsby-config.js, package.json, src/components/DataDuesAction/index.js, src/components/DataDuesAction/schema.js, yarn.lock
**What:** make address required in data dues form and remove netlify functions
**Why:** we want to have the address of all the people that completes the data dues form. netlify functions were disabled given:
1. we don't use this feature
2. was causing problems with the development server
**How:**
- remove netlify functions
- update validation schema to make address required
=> dev: make address required in data dues form

src/components/Layout.js
**What:** dev: identify user in fullstory.
**Why:** to attach user info to fullstory metrics.
**How:**
- https://help.fullstory.com/hc/en-us/articles/360020828113-FS-identify-Identifying-users
=> dev: identify user in fullstory

package.json, src/components/DataDuesAction/fields.js, yarn.lock
**What:**
Fix NaNNaNNaNNaN% in Data dues form. This happened when checking on **
I don't know my interest rate** and reloading the form.
https://www.loom.com/share/77721d49b2d247e49ea27ae8ea9df595
**Why:** Related to https://app.asana.com/0/1159164196409156/1159853987125729
**How:**
- Add special case when value of interest rate is **Unknown**.
- Update react-hook-form.
=> Fix NaNNaNNaNNaN% in Data dues form

package.json, src/sections/FAQ/index.js, yarn.lock
**What:** Open FAQ links in a new tab
https://www.loom.com/share/8e2c1cc4b5e144c28e8415b1a4e639cf
**Why:** Related to https://app.asana.com/0/1159164196409129/1169914199892361
**How:**
- use [`options.overrides`](https://github.com/probablyup/markdown-to-jsx#optionsoverrides---override-any-html-tags-representation) prop to pass configuration to the `a` tag
=> Open FAQ links in a new tab

.eslintrc.json, .prettierrc, README.md, package.json, src/cms/preview-templates/CollectionsPagePreview.js, src/cms/preview-templates/IndexPagePreview.js, src/sections/FAQ/index.js, src/sections/Hero/index.js, src/sections/Join/index.js, yarn.lock
**What:**
Add few improvements to make life easier for future devs
**Why:**
Before adding new fixes is good to have a solid foundation
**How:**
- Improve README
- Improve linting setup
- Fix CMS to render properly
=> Development improvements

src/components/DataDuesAction/index.js, src/components/DataDuesAction/styles.scss, src/components/Footer/style.scss, src/components/Profile/index.js, src/components/Profile/style.scss, src/pages/app/index.js, src/sections/CTA/style.scss, src/sections/CampaignActions/index.js, src/sections/CampaignActions/style.scss, src/sections/Notification/style.scss, src/styles/index.scss, src/styles/layout.scss
**What:**
Improve the way some composition are rendering for better aesthetics
**Why:**
Closes #15 
As there is a group of changes, I did a video of [Navigate thru strike campaign fixes](https://www.loom.com/share/de27c0e34e6348878037bd5026851904)
=> Overall layout fixes

package.json, yarn.lock
**What:**
Update header component to the latest version
**Why:**
Relates to: https://app.asana.com/0/1168997577035609/1198498074643140/f
**How:**
Updating the local dependency
=> feat(header-component): update header component to the latest version

package.json, src/components/Header/style.scss, yarn.lock
**What:**
Update header component package version
**Why:**
Relates to: https://app.asana.com/0/1159164196409156/1195530778765025/f
**How:**
Update the package locally to update the package.json and yarn.lock files
=> feat(header-component): update package version

src/sections/Hero/style.scss
**What:**
Change font color to action circles
**Why:**
Closes: https://app.asana.com/0/1159164196409156/1199211880645490/f
**How:**
Change styles to apply the `gray` font color
=> Change font color to action circles

src/components/CampaignWelcome/index.js
**What:**
Change the title of this section to match others
**Why:**
relates to https://app.asana.com/0/inbox/1191499079315083/1180381109182123/1199512241083384
[Screenshot of the change](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/2803c334-8ca0-4d2a-a320-4d4066f72566/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAT73L2G45O3KS52Y5%2F20210111%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20210111T131242Z&X-Amz-Expires=86400&X-Amz-Signature=55759c834e14aa1dbc9ad81ce27e84ee86f1dc3eac6a8a5352ba415939deb91c&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22)
[Previous state of this section](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/0809e28e-085a-4a24-a98d-4328e3d39544/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA …
=> fix(welcome): change title to be monospace

gatsby-config.js
**What:**
Update twitter username to StrikeDebt
**Why:**
Relates to: https://app.asana.com/0/1159164196409156/1199582929865335/f
**How:**
Replacing the old Twitter account with `StrikeDebt`
=> Update twitter username to StrikeDebt

package.json, yarn.lock
**What:**
Update header component package version
**Why:**
Relates to: https://app.asana.com/0/1159164196409129/1194694158783964/f
**How:**
Updating package locally
=> Update the header component package version
